/**
 * Trip data models — README "Stage 1 Data Models".
 *
 * These shapes are what Stage 2 will return from the API, so keep them free of
 * anything view-specific.
 */

export type ActivityCategory =
  | 'food'
  | 'nature'
  | 'culture'
  | 'adventure'
  | 'relaxation'
  | 'travel';

/**
 * A point on the earth.
 *
 * `lng`, not `lon` — OpenTripMap answers with `lon` and the conversion happens
 * at that service's boundary, so nothing downstream has to remember which.
 */
export type LatLng = {
  lat: number;
  lng: number;
};

export type ItineraryActivity = {
  id: string;
  /** Display time, e.g. "09:30". */
  time: string;
  title: string;
  description: string;
  category: ActivityCategory;
  priceEstimate?: number;
  image?: string;
  /**
   * Set when the entry was imported from the explorer rather than generated by
   * the planner. It is the OpenTripMap id, so the day can link back to the
   * attraction and a second import of the same place can be recognised.
   */
  sourceActivityId?: string;
  /** Carried over from the explorer so an imported stop can be mapped. */
  coordinates?: LatLng;
};

export type ItineraryDay = {
  id: string;
  dayNumber: number;
  /** ISO calendar date, `YYYY-MM-DD`. */
  date: string;
  destination: string;
  summary: string;
  activities: ItineraryActivity[];
  /**
   * The day's own point, when something knows it.
   *
   * Nothing writes this yet — the map derives a stop's position from its
   * activities or by geocoding the destination name. It stays because a day
   * that does carry a point should outrank both.
   */
  coordinates?: LatLng;
  /** Extension to the README model: the photo used on itinerary cards. */
  image?: string;
};

/**
 * @deprecated Bookings live in their own store — see `src/types/booking.types.ts`.
 *
 * Read exactly once, by `booking.migration.ts`, and never written again. Still
 * typed so that migration can read a trip saved before the move without a cast.
 */
export type LegacyBookingKind = 'hotel' | 'ticket' | 'activity';

/** @deprecated See {@link LegacyBookingKind}. */
export type LegacyTripBooking = {
  id: string;
  kind: LegacyBookingKind;
  title: string;
  /** ISO calendar date, `YYYY-MM-DD`. Empty when the trip has not fixed one. */
  date: string;
  /** Confirmation or reference number, as the provider issued it. */
  reference: string;
  /** What it cost, in the trip's own currency. Absent when not recorded. */
  price?: number;
  /** Where the confirmation lives, if it is on the web. */
  url?: string;
  /** ISO timestamp. */
  createdAt: string;
};

/** A free-text reminder kept with the trip. */
export type TripNote = {
  id: string;
  text: string;
  /** ISO timestamp. */
  createdAt: string;
  /** ISO timestamp; equal to `createdAt` until the note is edited. */
  updatedAt: string;
};

export type Trip = {
  id: string;
  /**
   * Identifies the generated draft this trip came from. Saving the same draft
   * twice returns the existing trip instead of creating a duplicate.
   * Optional so trips saved before this existed still load.
   */
  draftId?: string;
  title: string;
  /** Human label for the whole trip, e.g. "Bali" — what the cards show. */
  destination: string;
  /**
   * The destination split for the explorer, which has to ask a country-scoped
   * API. Both are optional: trips saved before these existed carry only
   * `destination`, and the explorer reads that as a city rather than
   * demanding a migration.
   */
  destinationCountry?: string;
  destinationCity?: string;
  /** ISO calendar date, `YYYY-MM-DD`. */
  startDate: string;
  /** ISO calendar date, `YYYY-MM-DD`. */
  endDate: string;
  travellers: number;
  coverImage: string;
  itinerary: ItineraryDay[];
  /**
   * @deprecated Migrated into the booking store on first load, then stripped.
   * Nothing but `booking.migration.ts` may read this.
   */
  bookings?: LegacyTripBooking[];
  /**
   * Reminders the traveller added themselves.
   *
   * Optional: a trip saved before notes existed carries none, and the tab
   * reads a missing list as an empty one rather than forcing a migration.
   * Notes stay on the trip — unlike bookings, they are meaningless without
   * one and are never read across trips.
   */
  notes?: TripNote[];
  flightsEstimate?: number;
  hotelsEstimate?: number;
  activitiesEstimate?: number;
  /** ISO timestamp. */
  createdAt: string;
  /** ISO timestamp. */
  updatedAt: string;
};

/**
 * A trip that has been generated but not persisted: the server (localStorage
 * in Stage 1) owns the id and timestamps.
 */
export type TripDraft = Omit<Trip, 'id' | 'createdAt' | 'updatedAt'>;
